name: avance1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  printing: ^5.14.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  intl: ^0.18.0
  image_picker: ^0.8.7+4
  diacritic: ^0.1.3

  #IA
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/fondo.jpg
    - assets/images/henry.jpg 
    - assets/images/logoescuela.jpg 
    - assets/images/cienciasNaturales.jpg
    - assets/images/cienciasSociales.jpg
    - assets/images/educacionFisica.jpg
    - assets/images/Español.jpg
    - assets/images/inglés.jpg
    - assets/images/ingles.jpg 
    - assets/images/Matematicas.jpg
    - assets/images/matematicas1.jpg
    - assets/images/profile.jpg
    - assets/images/profile_admin.jpg
    - assets/images/profile_estudiante.jpg
